sudo: required

services:
    - docker

language: bash

before_script:
    - docker version
    - docker-compose version
    - docker-compose pull
    - docker-compose up -d
  
script:
    - docker ps
    - docker network ls
    - docker volume ls
