sudo: required

services:
    - docker

language: bash

before_script:
    - docker-compose pull
    - docker-compose up -d
    - docker ps
    
script:
    - docker version
    - docker-compose version
    - docker volume ls