version: '3'
 
services:
   database:
     image: mariadb:10.0.29
     volumes:
       - volume_database:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=abc123
       - MYSQL_DATABASE=sito
       - MYSQL_USER=user_sito
       - MYSQL_PASSWORD=abc123
     ports:
       - "3306:3306"
     networks:
       - BackEnd
       
       

   sito:
     depends_on:
       - database
     image: wordpress:4.7.2-apache
     ports:
       - "80:80"
     restart: always
     volumes:
           - volume_sito:/var/www/html
     environment:
       - WORDPRESS_DB_HOST=database
       - WORDPRESS_DB_NAME=sito
       - WORDPRESS_DB_USER=user_sito
       - WORDPRESS_DB_PASSWORD=abc123
     networks:
       - FrontEnd
       - BackEnd
       
   prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheusdata:/etc/prometheus
     command:
         - '--config.file=/etc/prometheus/prometheus.yml'
     ports:
       - "9090:9090"
     links:
       - exporter
  
  
   exporter:
     image: prom/mysqld-exporter
     restart: always
     ports: 
       - "9104:9104"
     links:
       - database
     environment:
        DATA_SOURCE_NAME: "user_sito:abc123@(database:3306)/mysql"
     command: '--collect.global_variables --collect.slave_status --collect.binlog_size --collect.info_schema.innodb_metrics --collect.auto_increment.columns --collect.engine_tokudb_status --collect.info_schema.userstats --collect.info_schema.innodb_tablespaces --collect.info_schema.tablestats --collect.info_schema.tables --collect.info_schema.query_response_time --collect.info_schema.processlist --collect.perf_schema.eventsstatements --collect.perf_schema.indexiowaits --collect.perf_schema.tableiowaits --collect.perf_schema.tablelocks --collect.perf_schema.file_events --collect.perf_schema.eventswaits'  
 
 
  # grafana:
   #  image: grafana/grafana
    # ports:
     #  - '3000:3000'
    # volumes:
     #  - grafanadata:/var/lib/grafana
     #  - ./grafana/provisioning/:/etc/grafana/provisioning/
     #env_file:
      # - ./grafana/config.monitoring
     #restart: always

 

volumes:
    volume_database:
    volume_sito:
    #grafanadata:
    prometheusdata:
 
networks:
    FrontEnd:
      driver: bridge
    BackEnd:
      driver: bridge
